# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hollywood' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# Pods for Hollywood
pod 'Firebase/Core', '~> 3.15.0'
pod 'Firebase/Database'
pod 'Firebase/Crash'

  target 'HollywoodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HollywoodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
